name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths:
      - "infra/backend/**"
      - ".github/workflows/deploy-backend.yml"

jobs:
  deploy-artifacts-bucket:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::198226511774:role/GitHubActionsDeployRole
          aws-region: eu-north-1

      - name: Package Lambda
        run: |
          cd backend/visitor-counter
          zip -r ../../visitor-counter.zip .

      - name: Deploy Backend Stack
        run: |
          # Deploy CloudFormation stack
          aws cloudformation deploy \
            --stack-name backend-stack \
            --template-file infra/backend/backend-stack.yml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides LambdaArtifactKey=visitor-counter.zip

      - name: Upload Lambda artifact
        run: |
          BUCKET_NAME=$(aws cloudformation describe-stacks \
            --stack-name backend-stack \
            --query "Stacks[0].Outputs[?OutputKey=='ArtifactsBucketName'].OutputValue" \
            --output text)
          aws s3 cp visitor-counter.zip s3://$BUCKET_NAME/visitor-counter.zip

      - name: Debug CloudFormation Failure
        if: failure()
        run: |
          aws cloudformation describe-stack-events \
            --stack-name artifacts-bucket-stack \
            --query "StackEvents[?ResourceStatus=='CREATE_FAILED' || ResourceStatus=='REVIEW_IN_PROGRESS' || ResourceStatus=='ROLLBACK_IN_PROGRESS'].[LogicalResourceId, ResourceStatus, ResourceStatusReason]" \
            --output table
