name: identity-center-oicd

on:
  push:
    branches: [ main ]
    paths:
      - "infra/identity-center/**"

jobs:
  deploy-identity-center:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::123644281325:role/github-action-identity-center
          aws-region: eu-north-1

      - name: Deploy Identity Center Stack
        run: |
          aws cloudformation deploy \
            --template-file infra/identity-center/identity-center-stack.yml \
            --stack-name identity-center \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Debug CloudFormation Failure
        if: failure()
        run: |
          echo "CloudFormation stack failed â€” showing recent failure events:"
          aws cloudformation describe-stack-events \
            --stack-name identity-center \
            --query "StackEvents[?ResourceStatus=='CREATE_FAILED' || ResourceStatus=='ROLLBACK_FAILED'].[Timestamp,LogicalResourceId,ResourceStatus,ResourceStatusReason]" \
            --output table