name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths:
      - "infra/backend/**"
      - ".github/workflows/deploy-backend.yml"

jobs:
  deploy-artifacts-bucket:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::198226511774:role/GitHubActionsDeployRole
          aws-region: eu-north-1

      - name: Deploy artifacts bucket stack
        run: |
          aws cloudformation deploy \
            --stack-name artifacts-stack \
            --template-file infra/backend/artifacts-bucket.yml \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Get artifact bucket name
        id: bucket
        run: |
          echo "bucket=$(aws cloudformation describe-stacks \
            --stack-name artifacts-stack \
            --query "Stacks[0].Outputs[?OutputKey=='ArtifactBucketName'].OutputValue" \
            --output text)" >> $GITHUB_OUTPUT

      - name: Zip Lambda function
        run: |
          cd backend/visitor-counter
          zip -r ../../visitor-counter.zip .

      - name: Upload Lambda package
        run: |
          aws s3 cp visitor-counter.zip \
            s3://${{ steps.bucket.outputs.bucket }}/visitor-counter.zip

      - name: Deploy backend stack
        run: |
          aws cloudformation deploy \
            --stack-name backend-stack \
            --template-file infra/backend/backend-stack.yml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              ArtifactBucketName=${{ steps.bucket.outputs.bucket }} \
              ArtifactKey=visitor-counter.zip

      - name: Debug CloudFormation Failure
        if: failure()
        run: |
          aws cloudformation describe-stack-events \
            --stack-name backend-stack \
            --query "StackEvents[?ResourceStatus=='CREATE_FAILED' || ResourceStatus=='REVIEW_IN_PROGRESS' || ResourceStatus=='ROLLBACK_IN_PROGRESS'].[LogicalResourceId, ResourceStatus, ResourceStatusReason]" \
            --output table
