name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths:
      - "infra/backend/**"
      - "infra/monitoring/**"
      - ".github/workflows/deploy-backend.yml"
      - "backend/lambdas/**"

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::198226511774:role/GitHubActionsDeployRole
          aws-region: eu-north-1

      - name: Deploy artifacts bucket stack
        run: |
          aws cloudformation deploy \
            --stack-name artifacts-stack \
            --template-file infra/backend/artifacts-bucket.yml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              BucketName=my-bucket-artifacts-198226511774

      - name: Zip Visitor counter Lambda function
        run: |
          cd backend/lambdas/visitor_counter
          zip -r ../../../visitor-counter.zip .

      - name: Calculate Visitor counter Lambda hash
        id: visitor_counter_hash
        run: |
          ZIP_FILE="visitor-counter-$(sha256sum visitor-counter.zip | awk '{print $1}').zip"
          echo "zip_file=$ZIP_FILE" >> $GITHUB_OUTPUT

      - name: Upload Visitor counter Lambda to S3
        run: |
          aws s3 cp visitor-counter.zip s3://my-bucket-artifacts-198226511774/${{ steps.visitor_counter_hash.outputs.zip_file }}

      - name: Zip Slack notifier Lambda
        run: |
          cd backend/lambdas/slack_notifier
          zip -r ../../../slack-notifier.zip .

      - name: Calculate Slack notifier Lambda hash
        id: slack_notifier_hash
        run: |
          ZIP_FILE="slack-notifier-$(sha256sum slack-notifier.zip | awk '{print $1}').zip"
          echo "zip_file=$ZIP_FILE" >> $GITHUB_OUTPUT

      - name: Upload Slack notifier Lambda to S3
        run: |
          aws s3 cp slack-notifier.zip s3://my-bucket-artifacts-198226511774/${{ steps.slack_notifier_hash.outputs.zip_file }}


      - name: Deploy backend stack
        run: |
          aws cloudformation deploy \
            --stack-name backend-stack \
            --template-file infra/backend/backend-stack.yml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              ArtifactBucketName=my-bucket-artifacts-198226511774 \
              ArtifactKey=${{ steps.visitor_counter_hash.outputs.zip_file }} 

      - name: Initialize DynamoDB visitor count
        run: |
          EXISTS=$(aws dynamodb get-item \
            --table-name VisitorCounterIAC \
            --key '{"id": {"S": "visitor_count"}}' \
            --query "Item.id.S" \
            --output text 2>/dev/null || echo "None")

          if [ "$EXISTS" = "None" ]; then
            echo "Item does not exist — creating it..."
            aws dynamodb put-item \
              --table-name VisitorCounterIAC \
              --item '{"id": {"S": "visitor_count"}, "count": {"N": "0"}}'
          else
            echo "Item already exists — skipping initialization."
          fi

      - name: Debug CloudFormation Failure
        if: failure()
        run: |
          aws cloudformation describe-stack-events \
            --stack-name backend-stack \
            --query "StackEvents[?ResourceStatus=='CREATE_FAILED' || ResourceStatus=='ROLLBACK_IN_PROGRESS'].[LogicalResourceId, ResourceStatus, ResourceStatusReason]" \
            --output table

      - name: Deploy monitoring stack
        run: |
          aws cloudformation deploy \
            --stack-name monitoring-stack \
            --template-file infra/monitoring/monitoring-stack.yml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              LambdaFunctionToMonitor=VisitorCounterLambdaIAC \
              ArtifactBucketName=my-bucket-artifacts-198226511774 \
              ArtifactKey=${{ steps.slack_notifier_hash.outputs.zip_file }} 