name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths:
      - "infra/backend/**"
      - "infra/monitoring/**"
      - ".github/workflows/deploy-backend.yml"
      - "backend/lambdas/**"

      - "cypress/**"

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::198226511774:role/GitHubActionsBackendDeployRole
          aws-region: eu-north-1

      - name: Deploy artifacts bucket stack
        run: |
          aws cloudformation deploy \
            --stack-name artifacts-stack \
            --template-file infra/backend/artifacts-bucket.yml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              BucketName=my-bucket-artifacts-198226511774

      - name: Zip, hash and upload all lambdas
        run: |
          LAMBDAS=("visitor_counter" "slack_notifier")
          BUCKET="my-bucket-artifacts-198226511774"

          for LAMBDA in "${LAMBDAS[@]}"; do
            echo "Processing Lambda: $LAMBDA"

            ZIP_NAME="$LAMBDA.zip"
            cd backend/lambdas/"$LAMBDA"/
            zip -r ../../../"$ZIP_NAME" .
            cd ../../../
            HASHED_ZIP="$LAMBDA-$(sha256sum "$ZIP_NAME" | awk '{print $1}').zip"
            
            aws s3 cp "$ZIP_NAME" s3://$BUCKET/$HASHED_ZIP

            VAR_NAME=$(echo "${LAMBDA^^}_ZIP")
            echo "$VAR_NAME=$HASHED_ZIP" >> $GITHUB_ENV
          done

      - name: Deploy backend stack
        run: |
          aws cloudformation deploy \
            --stack-name backend-stack \
            --template-file infra/backend/backend-stack.yml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              ArtifactBucketName=my-bucket-artifacts-198226511774 \
              ArtifactKey=${{ env.VISITOR_COUNTER_ZIP }}

      - name: Initialize DynamoDB visitor count
        run: |
          EXISTS=$(aws dynamodb get-item \
            --table-name VisitorCounterIAC \
            --key '{"id": {"S": "visitor_count"}}' \
            --query "Item.id.S" \
            --output text 2>/dev/null || echo "None")

          if [ "$EXISTS" = "None" ]; then
            echo "Item does not exist — creating it..."
            aws dynamodb put-item \
              --table-name VisitorCounterIAC \
              --item '{"id": {"S": "visitor_count"}, "count": {"N": "0"}}'
          else
            echo "Item already exists — skipping initialization."
          fi

      - name: Debug CloudFormation Failure
        if: failure()
        run: |
          aws cloudformation describe-stack-events \
            --stack-name backend-stack \
            --query "StackEvents[?ResourceStatus=='CREATE_FAILED' || ResourceStatus=='ROLLBACK_IN_PROGRESS'].[LogicalResourceId, ResourceStatus, ResourceStatusReason]" \
            --output table

      - name: Deploy monitoring stack
        run: |
          aws cloudformation deploy \
            --stack-name monitoring-stack \
            --template-file infra/monitoring/monitoring-stack.yml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              LambdaFunctionToMonitor=VisitorCounterLambdaIAC \
              ArtifactBucketName=my-bucket-artifacts-198226511774 \
              ArtifactKey=${{ env.SLACK_NOTIFIER_ZIP }} 


  test-backend:
    name: Backend Smoke Tests
    runs-on: ubuntu-latest
    needs: deploy-backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies (Cypress)
        run: npm ci

      - name: Fetch API Gateway URL
        run: |
          URL=$(aws cloudformation describe-stacks \
            --stack-name backend-stack \
            --query "Stacks[0].Outputs[?OutputKey=='APIUrl'].OutputValue" \
            --output text)
          echo "CYPRESS_API_URL=$URL" >> $GITHUB_ENV

      - name: Run Backend API Smoke Tests
        uses: cypress-io/github-action@v6
        with:
          command: npm run cypress:run --spec 'cypress/e2e/api.cy.js'

