name: Deploy Static Content and Run Smoke Tests (S3/CloudFront and Cypress)

on:
  push:
    branches: [ main ]
    paths:
      - "site-content/**"

      - "cypress/**"
      - "package.json"
      - "package-lock.json"
      - "cypress.config.js"

      - ".github/workflows/static-site-content.yml"

jobs:
  deploy_content:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::198226511774:role/GitHubActionsContentDeployRole
          aws-region: eu-north-1

      - name: Upload Static Website Files to S3
        run: |
          # 1. Fetch the actual bucket name from the deployed stack outputs
          BUCKET_NAME=$(aws cloudformation describe-stacks \
            --stack-name static-site-stack \
            --query "Stacks[0].Outputs[?OutputKey=='StaticSiteBucketName'].OutputValue" \
            --output text)

          # 2. Use aws s3 sync to upload files
          aws s3 sync ./site-content s3://$BUCKET_NAME \
            --delete \
            --acl private \
            --exclude "infrastructure/*" 
            
          echo "Successfully synced files to s3://$BUCKET_NAME"

      - name: Invalidate CloudFront Cache
        run: |
          echo "Fetching CloudFront Distribution ID..."
          # 1. Fetch the Distribution ID from the deployed stack outputs
          DISTRIBUTION_ID=$(aws cloudformation describe-stacks \
            --stack-name static-site-stack \
            --query "Stacks[0].Outputs[?OutputKey=='StaticSiteDistributionId'].OutputValue" \
            --output text)

          # 2. Create the invalidation request for all paths
          aws cloudfront create-invalidation \
            --distribution-id $DISTRIBUTION_ID \
            --paths "/*"
          
          echo "CloudFront invalidation request sent for $DISTRIBUTION_ID."

  test:
    name: Smoke Test Deployment
    runs-on: ubuntu-latest
    needs: deploy_content
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (Cypress)
        run: npm ci

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          command: npm run cypress:run 
          wait-on: https://ivanovv.dev
        env:
          CYPRESS_BASE_URL: https://ivanovv.dev